dist: trusty
sudo: false

env:
  global:
    # This will be part of the release tarball
    - PROJECT_NAME="safedrive-sdk"
    - MAKE_DEB=no
    - DEB_MAINTAINER="Stephen Oliver <steve@infincia.com>"
    - DEB_DESCRIPTION="SafeDrive SDK"

addons:
  apt:
    packages:
      - musl-tools
      - musl-dev
      - linux-headers-generic

matrix:
  include:
    - os: linux
      env: TARGET=x86_64-unknown-linux-musl
    - os: linux
      env: TARGET=x86_64-unknown-linux-gnu
    - os: osx
      osx_image: xcode8.3
      env: TARGET=x86_64-apple-darwin


cache:
  directories:
    - src
    - dep
    - target
    - $HOME/.cargo

before_install:
  - export PATH="$PATH:$HOME/.cargo/bin"

install:
  - bash ci/install.sh

script:
  - travis_wait 30 bash unit.sh
  - bash release.sh

before_deploy:
  - bash ci/before_deploy.sh

deploy:
  provider: releases
  api_key:
    secure: uBQS6bf7gVRgC1RxsiRc8KraU5DhKar4JQkErrDc1K70XJm2FY8pfEXIj/kDbzbYmJ/PR5a+jNT3iW9WzBJx5azf1RvB82gHqVcTjsoH9o7udWlY2sMp7xnxKMumeWN+0bur75kVlWqm5C9jo8i26NjOKFRA1Dn3PTDHHqLlVPI32sTNOC7Q3aGEHss6QXvIAfBrjgwA3YRA2A8omrgJ2KUXstN6XRzV4g3U2BNg0Lb+X0MeunLORzY9Rj9gxqCeZART9XGGyt4JDfNKumhsV5BWJs5mhPFLF8XklaiqTFiIaNiQuVocyGWxdPVUQ7EECzzGw2MsBLBrWbAd6GVnuYyQMkJ/feBAd8cEbc4/itNcD1vwdGTgnOUT7Ii60nDOifKOX8WyrKAqsD2OuSvljylzzH7slUrwPIwhGOZLoqlYSHzZj4qXYwKBnq0SlXy0PLH9ruEYsz7yd/f6hOdHjtoSEQz+fJ/WiwRGLGOJ5kM+QsqZpJvOEKumWbkVgi+llXPSKHMlSuKgVHjXb/W641imT9uKL5igJceRIYRVPthpzj1FMuw/GqI/oCXj5fbIBHlXg5VmsJoSH62tIah94jjbz3f8IZNdECSY12UinCFO5uJ/olBN3HsZP8ZdR0P1g9BxE7m5PzvnmDpI1nif3/qdv250OjBJ7XnyIZGNZoQ=
  file_glob: true
  file: ${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}.*
  # don't delete the artifacts from previous phases
  skip_cleanup: true
  # deploy when a new tag is pushed
  on:
    tags: true

branches:
  only:
    # Pushes and PR to the master branch
    - master
    # IMPORTANT Ruby regex to match tags. Required, or travis won't trigger deploys when a new tag
    # is pushed. This regex matches semantic versions like v1.2.3-rc4+2016.02.22
    - /^v\d+\.\d+\.\d+.*$/

notifications:
  email:
    on_success: never