dist: trusty
sudo: false
osx_image: xcode8.3

env:
  global:
    # This will be part of the release tarball
    - PROJECT_NAME="safedrive-sdk"
    - MAKE_DEB=no
    - DEB_MAINTAINER="Stephen Oliver <steve@infincia.com>"
    - DEB_DESCRIPTION="SafeDrive SDK"
    - CONFIGURATION="Release"
    - secure: AXo5SekkixiisY7W9+ySPCkV58Fn3jCoMdV2gqXU4tL4U2Xk9j/IzB8Mi5o6F8QBiESvrR2gpMT8XWPieEpwXiFxakC5Z2X+o1e3UAKBIkOGZf32bbUsXhiBK4HfFyWgMwv1kFVUoCw+G7erDGt9bKmujVx1pt2ZJdTSDmwQhS9j7qvSNEts7bJOyIMM27u5c/37d4pOqkwUiP/EaBOcHbfdz8gIjRNuFPTfyntiCGXp9Zh8WDSds2QQJYZRb92zrlq8m45si2qHb9u8zaLKwVbZuHppPcKAWnUsS/WPUy8LdyeTKnvdZ1cSzbJ7f1prCKe80V2UFkiT66cHYzLtvFRLlKTbO7GQRaq/wLxlMchdhbp5TDu3oWFWUa6trrhd7mYnMasu40OL10r5+IS51eVe3JG7cZ8l0TfzMeaylHTqopZh7G+7igduHZ0bS97VioGhpMy3QvTiSg+E/KKXyPMwOjO4x2Ib4OA90RTtsbjyoUVIYwVmXErjlFWSIScd/lQgFipJw4tFNJVa4DJBDuh8axmY29nAtTlaVrOgitCm4ycYOSNMKaEAip7FVPdyK7pPIosYxd5HQGyUUHzcyKHKZ3fUjIadp7beQmiG433nJX6JHCWkwOfKGYUQcMco1/1PiJCYE65PP93BZBCue4mI7v5gzHwqo0/SwCPuzOQ=
    - secure: azB+o0ReqKZ5UvTOy2zFovyBNhR025ma8FMV/NaxNI1/nYQq6zAdZXd3DnJKh3po8vSYlROfRrGo/buow1SyT3znnfgwdOQuqJferCO0pocXN5IHvSteDNvr6oRPR8IrDGEgAFOUuaN/yoKHmFmEBWKFdeoe9/44Zo5uCd+DGl6as2KSyijUMiTmUFapq9zZboBGxzCPDndywPkaKzb6GtlwHUjd64EqYfK63JeNbd3AYokOjByjgWnH815SPNrUmRWV5f1Lp53houBGzzFBIcxg1x2r4qHl1LnrgqSFylAxLt6isxBBXWeWE88KWTi2+NSVMyJNfc6TbvkzExY3tza4zs/5VaM2XtbiPjCyrabcoz6FqlvzhWXzxataZKgbbMGYxpOnXk9c1aGJbLjPBx8eKN1VywgGP0bP121CbN5pHUuICJ6ogfva/n6QwzLK1Mn1buEBAhpRl4jQb+ML5tGbjVLcoXjoHwSLCSwSvNAfV1svP3u7h0JtbNl67AhSZIayUlSTPEgCV3TpwviIPIi6zMq5+zLaHXCN20vIr5cVxAV6WxXbvFDm5cs4kuRqsVQ3y1TRPMtGlA5nkMd0imThW4ZMFac6jarDR6YUA+lopUGs5TzDJ2UnmrIK8fZi1m/DGNfIk5MqdigCxnhkCR6Xx5F8C6ihAuuoeAJ6qI0=

addons:
  apt:
    packages:
      - musl-tools
      - musl-dev
      - linux-headers-generic
      - libssh2-1-dev
      - libdbus-1-dev
      - libssl-dev


matrix:
  include:
    #- os: linux
    #  env: TARGET=x86_64-unknown-linux-musl
    - os: linux
      env: TARGET=x86_64-unknown-linux-gnu
    - os: osx
      env: TARGET=x86_64-apple-darwin


cache:
  directories:
    - src
    - dep
    - target
    - $HOME/.cargo

before_install:
  - export PATH="$PATH:$HOME/.cargo/bin"

install:
  - bash ci/install.sh
  - find /usr/local -name '*fuse*'

script:
  - travis_wait 90 bash dep.sh
  - travis_wait 60 bash unit.sh
  - travis_wait 60 bash release.sh

before_deploy:
  - bash ci/before_deploy.sh

deploy:
  provider: releases
  api_key:
    secure: uBQS6bf7gVRgC1RxsiRc8KraU5DhKar4JQkErrDc1K70XJm2FY8pfEXIj/kDbzbYmJ/PR5a+jNT3iW9WzBJx5azf1RvB82gHqVcTjsoH9o7udWlY2sMp7xnxKMumeWN+0bur75kVlWqm5C9jo8i26NjOKFRA1Dn3PTDHHqLlVPI32sTNOC7Q3aGEHss6QXvIAfBrjgwA3YRA2A8omrgJ2KUXstN6XRzV4g3U2BNg0Lb+X0MeunLORzY9Rj9gxqCeZART9XGGyt4JDfNKumhsV5BWJs5mhPFLF8XklaiqTFiIaNiQuVocyGWxdPVUQ7EECzzGw2MsBLBrWbAd6GVnuYyQMkJ/feBAd8cEbc4/itNcD1vwdGTgnOUT7Ii60nDOifKOX8WyrKAqsD2OuSvljylzzH7slUrwPIwhGOZLoqlYSHzZj4qXYwKBnq0SlXy0PLH9ruEYsz7yd/f6hOdHjtoSEQz+fJ/WiwRGLGOJ5kM+QsqZpJvOEKumWbkVgi+llXPSKHMlSuKgVHjXb/W641imT9uKL5igJceRIYRVPthpzj1FMuw/GqI/oCXj5fbIBHlXg5VmsJoSH62tIah94jjbz3f8IZNdECSY12UinCFO5uJ/olBN3HsZP8ZdR0P1g9BxE7m5PzvnmDpI1nif3/qdv250OjBJ7XnyIZGNZoQ=
  file_glob: true
  file: ${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}.*
  # don't delete the artifacts from previous phases
  skip_cleanup: true
  # deploy when a new tag is pushed
  on:
    tags: true

branches:
  only:
    # Pushes and PR to the master branch
    - master
    # IMPORTANT Ruby regex to match tags. Required, or travis won't trigger deploys when a new tag
    # is pushed. This regex matches semantic versions like v1.2.3-rc4+2016.02.22
    - /^v\d+\.\d+\.\d+.*$/

notifications:
  email:
    on_success: never