environment:
  global:
    PROJECT_NAME: safedrive-sync-sdk
  matrix:
    # Stable channel
    - TARGET: i686-pc-windows-msvc
      CHANNEL: stable
      BIT: x86
      WIDTH: 32
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: stable
      BIT: x64
      WIDTH: 64

# Install Rust and Cargo
# (Based on from https://github.com/rust-lang/libc/blob/master/appveyor.yml)
install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
  - mkdir C:\Users\appveyor\libx86
  - mkdir C:\Users\appveyor\libx64
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin;
  - rustc -Vv
  - cargo -V
  - mkdir deps
  - nuget install zlib-msvc14-x86-master -Source https://ci.appveyor.com/nuget/zlib-shallow-x0n34b3pfq1b
  - ps: move zlib*\* deps -force
  - copy /y deps\zlibstatic.lib "C:\Users\appveyor\libx86"
  - ren C:\Users\appveyor\libx86\zlibstatic.lib z.lib
  - nuget install zlib-msvc14-x64-master -Source https://ci.appveyor.com/nuget/zlib-shallow-x0n34b3pfq1b
  - ps: move zlib*\* deps -force
  - copy /y deps\zlibstatic.lib "C:\Users\appveyor\libx64"
  - ren C:\Users\appveyor\libx64\zlibstatic.lib z.lib

# 'cargo test' takes care of building for us, so disable Appveyor's build stage. This prevents
# the "directory does not contain a project or solution file" error.
# source: https://github.com/starkat99/appveyor-rust/blob/master/appveyor.yml#L113
build: false

# Equivalent to Travis' `script` phase
# TODO modify this phase as you see fit
test_script:
  - unit.cmd

before_deploy:
  # Generate artifacts for release
  - release.cmd
  - mkdir dist-win-vs2015
  # TODO update this part to copy the artifacts that make sense for your project
  - copy target\release\libsdsync.lib dist-win-vs2015
  - copy target\release\safedrive dist-win-vs2015
  - cd dist-win-vs2015
    # release zipfile will look like 'rust-everywhere-v1.2.3-x86_64-pc-windows-msvc'
  - 7z a ../%PROJECT_NAME%-%APPVEYOR_REPO_TAG_NAME%-%TARGET%.zip *
  - appveyor PushArtifact ../%PROJECT_NAME%-%APPVEYOR_REPO_TAG_NAME%-%TARGET%.zip

deploy:
  description: 'SafeDrive SDK Windows'
  # All the zipped artifacts will be deployed
  artifact: /.*\.zip/
  # TODO Regenerate this auth_token for your project, this one won't work for you. Here's how:
  # - Go to 'https://github.com/settings/tokens/new' and generate a Token with only the
  # `public_repo` scope enabled
  # - Then go to 'https://ci.appveyor.com/tools/encrypt' and enter the newly generated token.
  # - Enter the "encrypted value" below
  auth_token:
    secure: cW2lNuSBqYoZhkWPcNmD/QQ5gyvXu7oM0etZqA9hvnu/BqRSWgDuiKvYWrGsHPIZ
  provider: GitHub
  # deploy when a new tag is pushed and only on the stable channel
  on:
    # channel to use to produce the release artifacts
    # NOTE make sure you only release *once* per target
    # TODO you may want to pick a different channel
    CHANNEL: stable
    appveyor_repo_tag: true

branches:
  only:
    - master
    # IMPORTANT Regex to match tags. Required, or appveyor may not trigger deploys when a new tag
    # is pushed. This regex matches semantic versions like v1.2.3-rc4+2016.02.22
    - /^v\d+\.\d+\.\d+.*$/