environment:
  global:
    PROJECT_NAME: safedrive-sdk
    TEST_USER:
      secure: l9NGI3oeUceB/UpM5Bnz1GZmXu+Ffqn8VpY1QrY5vKMayVSMKLbu3dDd+JGRYpcd
    TEST_PASSWORD:
      secure: 0KxiBlc00CJbHhy1jkz4Yg==
  matrix:
    - TARGET: i686-pc-windows-msvc
      PLATFORM: Win32
      ARCH: x86
      VS: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      TOOLSET: v141_xp
      ESCRIPT: v141_xp.bat
      CONFIGURATION: Release
    - TARGET: x86_64-pc-windows-msvc
      PLATFORM: x64
      ARCH: x64
      VS: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      TOOLSET: v141_xp
      ESCRIPT: v141_xp64.bat
      CONFIGURATION: Release

# Install Rust and Cargo
# (Based on from https://github.com/rust-lang/libc/blob/master/appveyor.yml)
install:
  - if defined VS call "%VS%" %ARCH%
  - if defined ESCRIPT call "%ESCRIPT%"
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin;
  - rustc -Vv
  - cargo -V
  - if not exist "%homepath%\.cargo\bin\cheddar.exe" cargo install moz-cheddar

# 'cargo test' takes care of building for us, so disable Appveyor's build stage. This prevents
# the "directory does not contain a project or solution file" error.
# source: https://github.com/starkat99/appveyor-rust/blob/master/appveyor.yml#L113
build: false

test_script:
  - unit.cmd %PLATFORM% %CONFIGURATION% %TOOLSET%

build_script:
  - release.cmd %PLATFORM% %CONFIGURATION% %TOOLSET%

before_deploy:
  - cd dist\%TARGET%\%TOOLSET%\%CONFIGURATION%
    # release zipfile will look like 'rust-everywhere-v1.2.3-x86_64-pc-windows-msvc'
  - 7z a ../%PROJECT_NAME%-%APPVEYOR_REPO_TAG_NAME%-%TARGET%-%TOOLSET%-%CONFIGURATION%.zip *
  - appveyor PushArtifact ../%PROJECT_NAME%-%APPVEYOR_REPO_TAG_NAME%-%TARGET%-%TOOLSET%-%CONFIGURATION%.zip

deploy:
  description: 'SafeDrive SDK'
  # All the zipped artifacts will be deployed
  artifact: /.*\.zip/
  # TODO Regenerate this auth_token for your project, this one won't work for you. Here's how:
  # - Go to 'https://github.com/settings/tokens/new' and generate a Token with only the
  # `public_repo` scope enabled
  # - Then go to 'https://ci.appveyor.com/tools/encrypt' and enter the newly generated token.
  # - Enter the "encrypted value" below
  auth_token:
    secure: cW2lNuSBqYoZhkWPcNmD/QQ5gyvXu7oM0etZqA9hvnu/BqRSWgDuiKvYWrGsHPIZ
  provider: GitHub
  # deploy when a new tag is pushed
  on:
    appveyor_repo_tag: true

branches:
  only:
    - master
    # IMPORTANT Regex to match tags. Required, or appveyor may not trigger deploys when a new tag
    # is pushed. This regex matches semantic versions like v1.2.3-rc4+2016.02.22
    - /^v\d+\.\d+\.\d+.*$/
