[package]
name = "sdsync"
version = "0.1.0"
authors = ["Stephen Oliver <steve@infincia.com>"]
build = "build.rs"

[profile.release]
debug = true

[dependencies]
sodiumoxide = "*"
rusqlite = "*"
libsqlite3-sys = "*"
time = "*"
uuid = { version = "0.3", features = ["v4"] }
libc = "*"
walkdir = "*"
cdc = "*"
tar = "*"
rustc-serialize = "*"
ssh2 = "*"
openssl = "*"
clap = "*"
reqwest = "*"
interfaces = "*"
serde = "0.8"
serde_json = "0.8"
bip39 = "*"

[build-dependencies]
rusty-cheddar = "0.3.3"

[lib]
name = "sdsync"
crate-type = ["rlib", "staticlib"]
doctest = false

[[bin]]
name = "sdsync"
path = "src/main.rs"
doc = false