[package]
name = "libsafedrive"
version = "0.3.8"
authors = ["Stephen Oliver <steve@infincia.com>"]
build = "build.rs"
workspace = ".."

[dependencies]
sodiumoxide = "*"
libc = "*"
walkdir = "*"
cdc = "*"
tar = "*"
rustc-serialize = "*"
reqwest = "*"
hyper = { version = "*" , default-features = false }
serde = "*"
serde_json = "*"
serde_derive = "*"
bip39 = "*"
rand = "*"
log = "*"
nom = "*"
lazy_static = "0.1.*"
uuid = { version = "*", features = ["v4"] }

[target.'cfg(target_os = "linux")'.dependencies]
openssl = "*"

[target.'cfg(target_os = "macos")'.dependencies]
objc = { version = "*", features = ["exception"] }
objc-foundation = "*"
interfaces = "*"


[build-dependencies]
rusty-cheddar = "*"

[lib]
name = "safedrive"
crate-type = ["lib", "staticlib", "cdylib"]
doctest = false
