[package]
name = "libsafedrive"
version = "0.2.8"
authors = ["Stephen Oliver <steve@infincia.com>"]
build = "build.rs"
workspace = ".."

[dependencies]
sodiumoxide = "*"
libc = "*"
walkdir = "*"
cdc = "*"
tar = "*"
rustc-serialize = "*"
reqwest = "*"
hyper = { version = "*" , default-features = false }
serde = "*"
serde_json = "*"
serde_derive = "*"
bip39 = "*"
rand = "*"
log = "*"

[target."cfg(not(windows))".dependencies]
interfaces = "*"

[target.'cfg(target_os = "linux")'.dependencies]
openssl = "*"

[build-dependencies]
rusty-cheddar = "*"

[lib]
name = "safedrive"
crate-type = ["lib", "staticlib", "cdylib"]
doctest = false
