[package]
name = "safedrive"
version = "0.3.8"
authors = ["Stephen Oliver <steve@infincia.com>"]
build = "build.rs"
workspace = ".."

[dependencies]
clap = "*"
pbr = "*"
rpassword = "*"
uuid = { version = "*", features = ["v4"] }
serde = "*"
serde_json = "*"
serde_derive = "*"
env_logger = "*"
log = "*"
prettytable-rs = "*"

[dependencies.libsafedrive]
path = "../libsafedrive"
