[package]
name = "safedrive"
version = "0.4.0"
authors = ["Stephen Oliver <steve@infincia.com>"]
build = "build.rs"
workspace = ".."

[dependencies]
clap = "*"
pbr = "^1.0.0-alpha.2"
rpassword = "*"
uuid = { version = "*", features = ["v4"] }
serde = "^0.9"
serde_json = "^0.9"
serde_derive = "^0.9"
env_logger = "*"
log = "*"
prettytable-rs = "*"
chrono = "^0.3"
number_prefix = "*"

[dependencies.libsafedrive]
path = "../libsafedrive"

[features]
default = []

keychain = []