[package]
name = "safedrive"
version = "0.1.0"
authors = ["Stephen Oliver <steve@infincia.com>"]
build = "build.rs"
workspace = ".."


[dependencies]
clap = "*"
pbr = "*"
rpassword = "*"
uuid = { version = "0.3", features = ["v4"] }


[dependencies.libsafedrive]
path = "../libsafedrive"