[package]
name = "safedrive"
version = "0.3.14"
authors = ["Stephen Oliver <steve@infincia.com>"]
build = "build.rs"
workspace = ".."

[dependencies]
clap = "*"
pbr = "*"
rpassword = "*"
uuid = { version = "*", features = ["v4"] }
serde = "^0.9"
serde_json = "^0.9"
serde_derive = "^0.9"
env_logger = "*"
log = "*"
prettytable-rs = "*"

[dependencies.libsafedrive]
path = "../libsafedrive"

[features]
default = []

keychain = []