[package]
name = "safedrive"
version = "0.2.5"
authors = ["Stephen Oliver <steve@infincia.com>"]
build = "build.rs"
workspace = ".."


[dependencies]
clap = "*"
pbr = "*"
rpassword = "*"
uuid = { version = "0.3", features = ["v4"] }
serde = "0.8"
serde_json = "0.8"
serde_derive = "0.8"
env_logger = "*"
log = "*"
prettytable-rs = "*"

[dependencies.libsafedrive]
path = "../libsafedrive"