[package]
name = "safedrived"
version = "0.3.17"
authors = ["Stephen Oliver <steve@infincia.com>"]
build = "build.rs"
workspace = ".."

[dependencies]
clap = "*"
serde = "^0.9"
serde_json = "^0.9"
serde_derive = "^0.9"
env_logger = "*"
log = "*"
prettytable-rs = "*"
tokio-inotify = "*"
futures = "*"
tokio-core = "*"

[dependencies.libsafedrive]
path = "../libsafedrive"
