[package]
name = "safedrived"
version = "0.3.8"
authors = ["Stephen Oliver <steve@infincia.com>"]
build = "build.rs"
workspace = ".."

[dependencies]
clap = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
env_logger = "*"
log = "*"
prettytable-rs = "*"
tokio-inotify = "*"
futures = "*"
tokio-core = "*"

[dependencies.libsafedrive]
path = "../libsafedrive"
