[package]
name = "builder"
version = "0.7.11"
authors = ["Stephen Oliver <steve@infincia.com>"]
build = "build.rs"
workspace = ".."

[dependencies]
clap = "*"
log = "*"
simplelog = "*"
subprocess = "*"
walkdir = "*"
fs_extra = "*"

[[bin]]
name = "builder"
